// Generated by CoffeeScript 1.4.0

this.App = (function() {

  function App() {
    window.scrollTo(0, 1);
    this.bindEvents();
    this.startTime();
  }

  App.prototype.bindEvents = function() {
    return $('#clock').on('click', function(e) {
      return this.stop();
    });
  };

  App.prototype.startTime = function() {
    var h, m, pillText, s, t, today,
      _this = this;
    today = new Date();
    h = today.getHours();
    m = today.getMinutes();
    s = today.getSeconds();
    m = this.checkTime(m);
    s = this.checkTime(s);
    $("#clock").text(h + ":" + m + ":" + s);
    pillText = "???";
    if (s >= 0 && s <= 5) {
      pillText = "jejum";
      $('.pill').hide();
      $("#jejum").show();
      this.play('jejum');
    } else if (s >= 10 && s <= 15) {
      pillText = "9 da manhã";
      $('.pill').hide();
      $("#manha").show();
      this.play('manha');
    } else if (s >= 20 && s <= 25) {
      pillText = "almoço";
      $('.pill').hide();
      $("#almoco").show();
      this.play('almoco');
    } else if (s >= 30 && s <= 35) {
      pillText = "4 da tarde";
      $('.pill').hide();
      $("#tarde").show();
      this.play('tarde');
    } else if (s >= 40 && s <= 45) {
      pillText = "9 da noite";
      $('.pill').hide();
      $("#noite").show();
      this.play('noite');
    } else {
      $('.pill').hide();
      $("#no-pill").show();
      pillText = "no pill";
      this.stop();
    }
    $(".pill .pill-text").text(pillText);
    t = setTimeout(function() {
      _this.startTime();
    }, 500);
  };

  App.prototype.checkTime = function(i) {
    if (i < 10) {
      i = "0" + i;
    }
    return i;
  };

  App.prototype.play = function(file) {
    /**
    For this to work on chrome for android, first this flag must be disabled:
    chrome://flags/#disable-gesture-requirement-for-media-playback
    */

    var media;
    media = $("." + file + "-mp3")[0];
    if (media.paused) {
      media.load();
      return media.play();
    }
  };

  App.prototype.stop = function() {
    $(".media").each(function(index) {
      if (!this.paused) {
        return this.pause();
      }
    });
  };

  return App;

})();
