// Generated by CoffeeScript 1.4.0

this.App = (function() {

  function App() {
    this.startTime();
  }

  App.prototype.startTime = function() {
    var h, m, pill, s, t, today,
      _this = this;
    today = new Date();
    h = today.getHours();
    m = today.getMinutes();
    s = today.getSeconds();
    m = this.checkTime(m);
    s = this.checkTime(s);
    document.getElementById("clock").innerHTML = h + ":" + m + ":" + s;
    pill = "???";
    if (s >= 0 && s <= 5) {
      pill = "jejum";
      $("#pill").addClass("jejum").removeClass("manha").removeClass("almoco").removeClass("noite");
      this.play();
    } else if (s >= 15 && s <= 20) {
      pill = "9 da manhã";
      $("#pill").removeClass("jejum").addClass("manha").removeClass("almoco").removeClass("noite");
      this.play();
    } else if (s >= 30 && s <= 35) {
      pill = "almoço";
      $("#pill").removeClass("jejum").removeClass("manha").addClass("almoco").removeClass("noite");
      this.play();
    } else if (s >= 45 && s <= 50) {
      pill = "9 da noite";
      $("#pill").removeClass("jejum").removeClass("manha").removeClass("almoco").addClass("noite");
      this.play();
    } else {
      pill = "";
      $("#pill").removeClass("jejum").removeClass("manha").removeClass("almoco").removeClass("noite");
      stop();
    }
    document.getElementById("pill").innerHTML = pill;
    t = setTimeout(function() {
      _this.startTime();
    }, 500);
  };

  App.prototype.checkTime = function(i) {
    if (i < 10) {
      i = "0" + i;
    }
    return i;
  };

  App.prototype.play = function() {
    /**
    For this to work on chrome for android, first this flag must be disabled:
    chrome://flags/#disable-gesture-requirement-for-media-playback
    */

  };

  App.prototype.stop = function() {
    $("#alarm-mp3")[0].pause();
  };

  return App;

})();
